name: news
channels:
  - conda-forge
  - defaults
  - stefanocorsi
  - anaconda-platform
dependencies:
  - colorama
  - rich
  - flashtext
  - numpy
  - transformers
  - python=3.9
  - pandas
  - mypy
  - pylint
  - pandas-stubs
  - types-colorama
