"""Inclusive New York City location vocabulary for first-filter evidence."""
from __future__ import annotations

import re


NYC_KEYWORDS: tuple[str, ...] = (
    "New York", "NYC", "Bronx", "Brooklyn", "Manhattan", "Queens",
    "Staten Island", "five boroughs",
    "Financial District", "Battery Park City", "Tribeca", "Civic Center",
    "Chinatown", "Two Bridges", "SoHo", "Little Italy", "Hudson Square",
    "Lower East Side", "East Village", "Greenwich Village", "West Village",
    "NoHo", "Nolita", "Bowery", "Gramercy", "Union Square", "Flatiron",
    "Chelsea", "Meatpacking District", "Hudson Yards", "Hell's Kitchen",
    "Clinton", "Garment District", "Times Square", "Midtown", "Murray Hill",
    "Kips Bay", "Turtle Bay", "Stuyvesant Town", "Peter Cooper Village",
    "Upper East Side", "Carnegie Hill", "Lenox Hill", "Yorkville",
    "Upper West Side", "Lincoln Square", "Morningside Heights",
    "Harlem", "Hamilton Heights", "Sugar Hill", "Washington Heights",
    "Inwood", "Roosevelt Island", "Mott Haven", "Melrose", "Port Morris",
    "Hunts Point", "Longwood", "Morrisania", "Crotona", "Highbridge",
    "Concourse", "Fordham", "University Heights", "Belmont", "East Tremont",
    "West Farms", "Kingsbridge", "Bedford Park", "Riverdale", "Fieldston",
    "Parkchester", "Soundview", "Throgs Neck", "Co-op City", "Morris Park",
    "Williamsbridge", "Baychester", "Pelham Bay", "City Island", "Castle Hill",
    "DUMBO",
    "Vinegar Hill", "Fort Greene", "Boerum Hill", "Cobble Hill",
    "Carroll Gardens", "Williamsburg", "Greenpoint",
    "Bushwick", "Bedford-Stuyvesant", "Bed-Stuy", "Ocean Hill",
    "Starrett City", "Spring Creek", "Crown Heights", "Prospect Heights",
    "Lefferts Gardens", "Brownsville", "Flatbush", "Canarsie",
    "Flatlands", "Park Slope", "Gowanus", "Sunset Park", "Bay Ridge",
    "Dyker Heights", "Bensonhurst", "Borough Park", "Coney Island",
    "Brighton Beach", "Gravesend", "Sheepshead Bay", "Midwood", "Marine Park",
    "Prospect Park", "Long Island City", "LIC", "Astoria", "Sunnyside",
    "Woodside", "Jackson Heights", "Elmhurst", "Corona",
    "Ridgewood", "Maspeth", "Middle Village", "Rego Park", "Forest Hills",
    "Kew Gardens", "Flushing", "Whitestone", "College Point", "Fresh Meadows",
    "Hillcrest", "Jamaica", "Hollis", "St. Albans", "Bellerose", "Bayside",
    "Little Neck", "Howard Beach", "Ozone Park", "Rockaway", "Broad Channel",
    "St. George", "Tompkinsville", "Stapleton",
    "Clifton", "Rosebank", "South Beach", "New Brighton", "Randall Manor",
    "Port Richmond", "Mariners Harbor", "Elm Park", "Westerleigh",
    "Castleton Corners", "New Springville", "Graniteville", "Tottenville",
    "Great Kills", "Huguenot", "Annadale", "Eltingville", "Oakwood", "Travis",
    "Todt Hill", "Richmondtown", "LaGuardia", "JFK", "Kennedy Airport",
    "Central Park", "Van Cortlandt Park", "Forest Park", "Broadway", "Wall Street",
    "Fifth Avenue", "Madison Avenue", "Park Avenue", "East River", "Hudson River",
    "George Washington Bridge", "Holland Tunnel", "Lincoln Tunnel", "Grand Central",
    "Penn Station", "Moynihan Train Hall", "Port Authority", "World Trade Center",
    "Empire State Building", "Rockefeller Center", "Chrysler Building",
    "Madison Square Garden", "Lincoln Center", "Radio City Music Hall", "Carnegie Hall",
    "Apollo Theater", "Metropolitan Museum", "Museum of Modern Art", "MoMA",
    "American Museum of Natural History", "Columbia University", "NYU",
    "Yankee Stadium", "Citi Field", "Barclays Center",
    "Bellevue Hospital", "Mount Sinai Hospital", "NewYork-Presbyterian",
    "Rikers Island", "United Nations",
)

NYC_REGEX = re.compile(
    r"\b(?:" + "|".join(re.escape(term) for term in NYC_KEYWORDS) + r")\b",
    re.IGNORECASE,
)
