"""
This type stub file was generated by pyright.
"""

from typing import Any, Iterable, List, Literal, Optional, Union
from splink.internals.column_expression import ColumnExpression
from splink.internals.comparison_creator import ComparisonCreator
from splink.internals.comparison_level_creator import ComparisonLevelCreator
from splink.internals.comparison_level_library import DateMetricType
from splink.internals.dialects import SplinkDialect

class ExactMatch(ComparisonCreator):
    """
    Represents a comparison of the data in `col_name` with two levels:

    - Exact match in `col_name`
    - Anything else

    Args:
        col_name (str): The name of the column to compare
    """
    def __init__(self, col_name: str) -> None:
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class LevenshteinAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, distance_threshold_or_thresholds: Union[Iterable[int], int] = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with three or more levels:

        - Exact match in `col_name`
        - Levenshtein levels at specified distance thresholds
        - ...
        - Anything else

        For example, with distance_threshold_or_thresholds = [1, 3] the levels are

        - Exact match in `col_name`
        - Levenshtein distance in `col_name` <= 1
        - Levenshtein distance in `col_name` <= 3
        - Anything else

        Args:
            col_name (str): The name of the column to compare
            distance_threshold_or_thresholds (Union[int, list], optional): The
                threshold(s) to use for the levenshtein similarity level(s).
                Defaults to [1, 2].
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class DamerauLevenshteinAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, distance_threshold_or_thresholds: Union[Iterable[int], int] = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with three or more levels:

        - Exact match in `col_name`
        - Damerau-Levenshtein levels at specified distance thresholds
        - ...
        - Anything else

        For example, with distance_threshold_or_thresholds = [1, 3] the levels are

        - Exact match in `col_name`
        - Damerau-Levenshtein distance in `col_name` <= 1
        - Damerau-Levenshtein distance in `col_name` <= 3
        - Anything else

        Args:
            col_name (str): The name of the column to compare.
            distance_threshold_or_thresholds (Union[int, list], optional): The
                threshold(s) to use for the Damerau-Levenshtein similarity level(s).
                Defaults to [1, 2].
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_description(self) -> str:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class JaccardAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, score_threshold_or_thresholds: Union[Iterable[float], float] = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with three or more levels:

        - Exact match in `col_name`
        - Jaccard score levels at specified thresholds
        - ...
        - Anything else

        For example, with score_threshold_or_thresholds = [0.9, 0.7] the levels are:

        - Exact match in `col_name`
        - Jaccard score in `col_name` >= 0.9
        - Jaccard score in `col_name` >= 0.7
        - Anything else

        Args:
            col_name (str): The name of the column to compare.
            score_threshold_or_thresholds (Union[float, list], optional): The
                threshold(s) to use for the Jaccard similarity level(s).
                Defaults to [0.9, 0.7].
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class JaroAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, score_threshold_or_thresholds: Union[Iterable[float], float] = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with three or more levels:

        - Exact match in `col_name`
        - Jaro score levels at specified thresholds
        - ...
        - Anything else

        For example, with score_threshold_or_thresholds = [0.9, 0.7] the levels are:

        - Exact match in `col_name`
        - Jaro score in `col_name` >= 0.9
        - Jaro score in `col_name` >= 0.7
        - Anything else

        Args:
            col_name (str): The name of the column to compare.
            score_threshold_or_thresholds (Union[float, list], optional): The
                threshold(s) to use for the Jaro similarity level(s).
                Defaults to [0.9, 0.7].
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class JaroWinklerAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, score_threshold_or_thresholds: Union[Iterable[float], float] = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with three or more levels:

        - Exact match in `col_name`
        - Jaro-Winkler score levels at specified thresholds
        - ...
        - Anything else

        For example, with score_threshold_or_thresholds = [0.9, 0.7] the levels are:

        - Exact match in `col_name`
        - Jaro-Winkler score in `col_name` >= 0.9
        - Jaro-Winkler score in `col_name` >= 0.7
        - Anything else

        Args:
            col_name (str): The name of the column to compare.
            score_threshold_or_thresholds (Union[float, list], optional): The
                threshold(s) to use for the Jaro-Winkler similarity level(s).
                Defaults to [0.9, 0.7].
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class DistanceFunctionAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, distance_function_name: str, distance_threshold_or_thresholds: Union[Iterable[float], float], higher_is_more_similar: bool = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with three or more levels:

        - Exact match in `col_name`
        - Custom distance function levels at specified thresholds
        - ...
        - Anything else

        For example, with distance_threshold_or_thresholds = [1, 3]
        and distance_function 'hamming', with higher_is_more_similar False
        the levels are:

        - Exact match in `col_name`
        - Hamming distance of `col_name` <= 1
        - Hamming distance of `col_name` <= 3
        - Anything else

        Args:
            col_name (str): The name of the column to compare.
            distance_function_name (str): the name of the SQL distance function
            distance_threshold_or_thresholds (Union[float, list], optional): The
                threshold(s) to use for the distance function level(s).
            higher_is_more_similar (bool): Are higher values of the distance function
                more similar? (e.g. True for Jaro-Winkler, False for Levenshtein)
                Default is True
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class PairwiseStringDistanceFunctionAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, distance_function_name: Literal["levenshtein", "damerau_levenshtein", "jaro_winkler", "jaro"], distance_threshold_or_thresholds: Union[Iterable[int | float], int | float]) -> None:
        """
        Represents a comparison of the *most similar pair* of values
        where the first value is in the array data in `col_name` for the first record
        and the second value is in the array data in `col_name` for the second record.
        The comparison has three or more levels:

        - Exact match between any pair of values
        - User-selected string distance function levels at specified thresholds
        - ...
        - Anything else

        For example, with distance_threshold_or_thresholds = [1, 3]
        and distance_function 'levenshtein' the levels are:

        - Exact match between any pair of values
        - Levenshtein distance between the most similar pair of values <= 1
        - Levenshtein distance between the most similar pair of values <= 3
        - Anything else

        Args:
            col_name (str): The name of the column to compare.
            distance_function_name (str): the name of the string distance function.
                Must be one of "levenshtein," "damera_levenshtein," "jaro_winkler,"
                or "jaro."
            distance_threshold_or_thresholds (Union[float, list], optional): The
                threshold(s) to use for the distance function level(s).
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_description(self) -> str:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class AbsoluteTimeDifferenceAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, *, input_is_string: bool, metrics: Union[DateMetricType, List[DateMetricType]], thresholds: Union[int, float, List[Union[int, float]]], datetime_format: str = ..., term_frequency_adjustments: bool = ..., invalid_dates_as_null: bool = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with multiple levels based on
        absolute time differences:

        - Exact match in `col_name`
        - Absolute time difference levels at specified thresholds
        - ...
        - Anything else

        For example, with metrics = ['day', 'month'] and thresholds = [1, 3] the levels
        are:

        - Exact match in `col_name`
        - Absolute time difference in `col_name` <= 1 day
        - Absolute time difference in `col_name` <= 3 months
        - Anything else

        This comparison uses the AbsoluteTimeDifferenceLevel, which computes the total
        elapsed time between two dates, rather than counting calendar intervals.

        Args:
            col_name (str): The name of the column to compare.
            input_is_string (bool): If True, the input dates are treated as strings
                and parsed according to `datetime_format`.
            metrics (Union[DateMetricType, List[DateMetricType]]): The unit(s) of time
                to use when comparing dates. Can be 'second', 'minute', 'hour', 'day',
                'month', or 'year'.
            thresholds (Union[int, float, List[Union[int, float]]]): The threshold(s)
                to use for the time difference level(s).
            datetime_format (str, optional): The format string for parsing dates if
                `input_is_string` is True. ISO 8601 format used if not provided.
            term_frequency_adjustments (bool, optional): Whether to apply term frequency
                adjustments. Defaults to False.
            invalid_dates_as_null (bool, optional): If True and `input_is_string` is
                True, treat invalid dates as null. Defaults to True.
        """
        ...
    
    @property
    def datetime_parse_function(self): # -> Callable[..., ColumnExpression]:
        ...
    
    @property
    def cll_class(self): # -> type[AbsoluteTimeDifferenceLevel]:
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class AbsoluteDateDifferenceAtThresholds(AbsoluteTimeDifferenceAtThresholds):
    @property
    def datetime_parse_function(self): # -> Callable[..., ColumnExpression]:
        ...
    
    @property
    def cll_class(self): # -> type[AbsoluteDateDifferenceLevel]:
        ...
    


class ArrayIntersectAtSizes(ComparisonCreator):
    def __init__(self, col_name: str, size_threshold_or_thresholds: Union[Iterable[int], int] = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with multiple levels based on
        the intersection sizes of array elements:

        - Intersection at specified size thresholds
        - ...
        - Anything else

        For example, with size_threshold_or_thresholds = [3, 1], the levels are:

        - Intersection of arrays in `col_name` has at least 3 elements
        - Intersection of arrays in `col_name` has at least 1 element
        - Anything else (e.g., empty intersection)

        Args:
            col_name (str): The name of the column to compare.
            size_threshold_or_thresholds (Union[int, list[int]], optional): The
                size threshold(s) for the intersection levels.
                Defaults to [1].
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class DistanceInKMAtThresholds(ComparisonCreator):
    def __init__(self, lat_col: str, long_col: str, km_thresholds: Union[Iterable[float], float]) -> None:
        """
        A comparison of the latitude, longitude coordinates defined in
        'lat_col' and 'long col' giving the great circle distance between them in km.

        An example of the output with km_thresholds = [1, 10] would be:

        - The two coordinates are within 1 km of one another
        - The two coordinates are within 10 km of one another
        - Anything else (i.e. the distance between coordinates are > 10km apart)

        Args:
            lat_col (str): The name of the latitude column to compare.
            long_col (str): The name of the longitude column to compare.
            km_thresholds (iterable[float] | float): The km threshold(s) for the
                distance levels.
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class CustomComparison(ComparisonCreator):
    def __init__(self, comparison_levels: List[Union[ComparisonLevelCreator, dict[str, Any]]], output_column_name: str = ..., comparison_description: str = ...) -> None:
        """
        Represents a comparison of the data with custom supplied levels.

        Args:
            output_column_name (str): The column name to use to refer to this comparison
            comparison_levels (list): A list of some combination of
                `ComparisonLevelCreator` objects, or dicts. These represent the
                similarity levels assessed by the comparison, in order of decreasing
                specificity
            comparison_description (str, optional): An optional description of the
                comparison
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> Optional[str]:
        ...
    


class _DamerauLevenshteinIfSupportedElseLevenshteinLevel(ComparisonLevelCreator):
    def __init__(self, col_name: Union[str, ColumnExpression], distance_threshold: int) -> None:
        ...
    
    def create_sql(self, sql_dialect: SplinkDialect) -> str:
        ...
    
    def create_label_for_charts(self) -> str:
        ...
    


class DateOfBirthComparison(ComparisonCreator):
    def __init__(self, col_name: Union[str, ColumnExpression], *, input_is_string: bool, datetime_thresholds: Union[int, float, List[Union[int, float]]] = ..., datetime_metrics: Union[DateMetricType, List[DateMetricType]] = ..., datetime_format: str = ..., invalid_dates_as_null: bool = ...) -> None:
        """
        Generate an 'out of the box' comparison for a date of birth column
        in the `col_name` provided.

        Note that `input_is_string` is a required argument: you must denote whether the
        `col_name` contains if of type date/dattime or string.

        The default arguments will give a comparison with comparison levels:

        - Exact match (all other dates)
        - Damerau-Levenshtein distance <= 1
        - Date difference <= 1 month
        - Date difference <= 1 year
        - Date difference <= 10 years
        - Anything else

        Args:
            col_name (Union[str, ColumnExpression]): The column name
            input_is_string (bool): If True, the provided `col_name` must be of type
                string.  If False, it must be a date or datetime.
            datetime_thresholds (Union[int, float, List[Union[int, float]]], optional):
                Numeric thresholds for date differences. Defaults to [1, 1, 10].
            datetime_metrics (Union[DateMetricType, List[DateMetricType]], optional):
                Metrics for date differences. Defaults to ["month", "year", "year"].
            datetime_format (str, optional): The datetime format used to cast strings
                to dates.  Only used if input is a string.
            invalid_dates_as_null (bool, optional): If True, treat invalid dates as null
                as opposed to allowing e.g. an exact or levenshtein match where one side
                or both are an invalid date.  Only used if input is a string.  Defaults
                to True.
        """
        ...
    
    @property
    def datetime_parse_function(self): # -> Callable[..., ColumnExpression]:
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class PostcodeComparison(ComparisonCreator):
    SECTOR_REGEX = ...
    DISTRICT_REGEX = ...
    AREA_REGEX = ...
    VALID_POSTCODE_REGEX = ...
    def __init__(self, col_name: Union[str, ColumnExpression], *, invalid_postcodes_as_null: bool = ..., lat_col: Union[str, ColumnExpression] = ..., long_col: Union[str, ColumnExpression] = ..., km_thresholds: Union[float, List[float]] = ...) -> None:
        """
        Generate an 'out of the box' comparison for a postcode column with the
        in the `col_name` provided.

        The default comparison levels are:

        - Null comparison
        - Exact match on full postcode
        - Exact match on sector
        - Exact match on district
        - Exact match on area
        - Distance in km (if lat_col and long_col are provided)

        It's also possible to include levels for distance in km, but this requires
        you to have geocoded your postcodes prior to importing them into Splink. Use
        the `lat_col` and `long_col` arguments to tell Splink where to find the
        latitude and longitude columns.

        See https://ideal-postcodes.co.uk/guides/uk-postcode-format
        for definitions

        Args:
            col_name (Union[str, ColumnExpression]): The column name or expression for
                the postcodes to be compared.
            invalid_postcodes_as_null (bool, optional): If True, treat invalid postcodes
                as null. Defaults to False.
            lat_col (Union[str, ColumnExpression], optional): The column name or
                expression for latitude. Required if `km_thresholds` is provided.
            long_col (Union[str, ColumnExpression], optional): The column name or
                expression for longitude. Required if `km_thresholds` is provided.
            km_thresholds (Union[float, List[float]], optional): Thresholds for distance
                in kilometers. If provided, `lat_col` and `long_col` must also be
                provided.
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class EmailComparison(ComparisonCreator):
    USERNAME_REGEX = ...
    DOMAIN_REGEX = ...
    def __init__(self, col_name: Union[str, ColumnExpression]) -> None:
        """
        Generate an 'out of the box' comparison for an email address column with the
        in the `col_name` provided.

        The default comparison levels are:

        - Null comparison: e.g., one email is missing or invalid.
        - Exact match on full email: e.g., `john@smith.com` vs. `john@smith.com`.
        - Exact match on username part of email: e.g., `john@company.com` vs.
        `john@other.com`.
        - Jaro-Winkler similarity > 0.88 on full email: e.g., `john.smith@company.com`
        vs. `john.smyth@company.com`.
        - Jaro-Winkler similarity > 0.88 on username part of email: e.g.,
        `john.smith@company.com` vs. `john.smyth@other.com`.
        - Anything else: e.g., `john@company.com` vs. `rebecca@other.com`.

        Args:
            col_name (Union[str, ColumnExpression]): The column name or expression for
                the email addresses to be compared.
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class NameComparison(ComparisonCreator):
    def __init__(self, col_name: Union[str, ColumnExpression], *, jaro_winkler_thresholds: Union[float, list[float]] = ..., dmeta_col_name: str = ...) -> None:
        """
        Generate an 'out of the box' comparison for a name column in the `col_name`
        provided.

        It's also possible to include a level for a dmetaphone match, but this requires
        you to derive a dmetaphone column prior to importing it into Splink. Note
        this is expected to be a column containing arrays of dmetaphone values, which
        are of length 1 or 2.

        The default comparison levels are:

        - Null comparison
        - Exact match
        - Jaro-Winkler similarity > 0.92
        - Jaro-Winkler similarity > 0.88
        - Jaro-Winkler similarity > 0.70
        - Anything else

        Args:
            col_name (Union[str, ColumnExpression]): The column name or expression for
                the names to be compared.
            jaro_winkler_thresholds (Union[float, list[float]], optional): Thresholds
                for Jaro-Winkler similarity. Defaults to [0.92, 0.88, 0.7].
            dmeta_col_name (str, optional): The column name for dmetaphone values.
                If provided, array intersection level is included. This column must
                contain arrays of dmetaphone values, which are of length 1 or 2.
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class ForenameSurnameComparison(ComparisonCreator):
    def __init__(self, forename_col_name: Union[str, ColumnExpression], surname_col_name: Union[str, ColumnExpression], *, jaro_winkler_thresholds: Union[float, list[float]] = ..., forename_surname_concat_col_name: str = ...) -> None:
        """
        Generate an 'out of the box' comparison for forename and surname columns
        in the `forename_col_name` and `surname_col_name` provided.

        It's recommended to derive an additional column containing a concatenated
        forename and surname column so that term frequencies can be applied to the
        full name.  If you have derived a column, provide it at
        `forename_surname_concat_col_name`.

        The default comparison levels are:

        - Null comparison on both forename and surname
        - Exact match on both forename and surname
        - Columns reversed comparison (forename and surname swapped)
        - Jaro-Winkler similarity > 0.92 on both forename and surname
        - Jaro-Winkler similarity > 0.88 on both forename and surname
        - Exact match on surname
        - Exact match on forename
        - Anything else

        Args:
            forename_col_name (Union[str, ColumnExpression]): The column name or
                expression for the forenames to be compared.
            surname_col_name (Union[str, ColumnExpression]): The column name or
                expression for the surnames to be compared.
            jaro_winkler_thresholds (Union[float, list[float]], optional): Thresholds
                for Jaro-Winkler similarity. Defaults to [0.92, 0.88].
            forename_surname_concat_col_name (str, optional): The column name for
                concatenated forename and surname values. If provided, term
                frequencies are applied on the exact match using this column
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


class CosineSimilarityAtThresholds(ComparisonCreator):
    def __init__(self, col_name: str, score_threshold_or_thresholds: Union[Iterable[float], float] = ...) -> None:
        """
        Represents a comparison of the data in `col_name` with two or more levels:

        - Cosine similarity levels at specified thresholds
        - ...
        - Anything else

        For example, with score_threshold_or_thresholds = [0.9, 0.7] the levels are:

        - Cosine similarity in `col_name` >= 0.9
        - Cosine similarity in `col_name` >= 0.7
        - Anything else

        Args:
            col_name (str): The name of the column to compare.
            score_threshold_or_thresholds (Union[float, list], optional): The
                threshold(s) to use for the cosine similarity level(s).
                Defaults to [0.9, 0.7].
        """
        ...
    
    def create_comparison_levels(self) -> List[ComparisonLevelCreator]:
        ...
    
    def create_output_column_name(self) -> str:
        ...
    


