"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod
from collections.abc import Sequence
from typing import Any, Dict, Generic, List, Optional, TypeVar, Union, final
from pandas import DataFrame as PandasDataFrame
from splink.internals.pipeline import CTEPipeline
from splink.internals.splink_dataframe import SplinkDataFrame
from splink.internals.dialects import SplinkDialect

logger = ...
AcceptableInputTableType = Union[str, PandasDataFrame, List[Dict[str, Any]], Dict[str, Any]]
TablishType = TypeVar("TablishType")
T = TypeVar("T")
class DatabaseAPI(ABC, Generic[TablishType]):
    sql_dialect: SplinkDialect
    debug_mode: bool = ...
    def __init__(self) -> None:
        ...
    
    @final
    def sql_to_splink_dataframe_checking_cache(self, sql: str, output_tablename_templated: str, use_cache: bool = ...) -> SplinkDataFrame:
        ...
    
    def sql_pipeline_to_splink_dataframe(self, pipeline: CTEPipeline, use_cache: bool = ...) -> SplinkDataFrame:
        """
        Execute a given pipeline using input_dataframes as seeds if provided.
        self.debug_mode controls whether this is CTE or individual tables.
        pipeline is set to spent after execution ensuring it cannot be
        acidentally reused
        """
        ...
    
    @final
    def register_multiple_tables(self, input_tables: Sequence[AcceptableInputTableType], input_aliases: Optional[List[str]] = ..., overwrite: bool = ...) -> Dict[str, SplinkDataFrame]:
        ...
    
    @final
    def register_table(self, input_table: AcceptableInputTableType, table_name: str, overwrite: bool = ...) -> SplinkDataFrame:
        ...
    
    def delete_table_from_database(self, name: str) -> None:
        ...
    
    @abstractmethod
    def table_to_splink_dataframe(self, templated_name: str, physical_name: str) -> SplinkDataFrame:
        ...
    
    @abstractmethod
    def table_exists_in_database(self, table_name: str) -> bool:
        """
        Check if table_name exists in the backend
        """
        ...
    
    def process_input_tables(self, input_tables: Sequence[AcceptableInputTableType]) -> Sequence[AcceptableInputTableType]:
        """
        Process list of input tables from whatever form they arrive in to that suitable
        for linker.
        Default just passes through - backends can specialise if desired
        """
        ...
    
    def remove_splinkdataframe_from_cache(self, splink_dataframe: SplinkDataFrame) -> None:
        ...
    
    def delete_tables_created_by_splink_from_db(self): # -> None:
        ...
    


DatabaseAPISubClass = DatabaseAPI[Any]
