"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Any
from splink.internals.database_api import DatabaseAPISubClass
from splink.internals.settings_creator import SettingsCreator

logger = ...
class Linker:
    """The Linker object manages the data linkage process and holds the data linkage
    model.

    Most of Splink's functionality can  be accessed by calling methods (functions)
    on the linker, such as `linker.predict()`, `linker.profile_columns()` etc.

    The Linker class is intended for subclassing for specific backends, e.g.
    a `DuckDBLinker`.
    """
    training: Any
    inference: Any
    clustering: Any
    visualisations: Any
    def __init__(self, input_table_or_tables: str | list[str], settings: SettingsCreator | dict[str, Any] | Path | str, db_api: DatabaseAPISubClass, set_up_basic_logging: bool = ..., input_table_aliases: str | list[str] | None = ..., validate_settings: bool = ...) -> None:
        """
        Initialise the linker object, which manages the data linkage process and
        holds the data linkage model.

        Examples:

            Dedupe
            ```py
            linker = Linker(df, settings_dict, db_api)
            ```
            Link
            ```py
            df_1 = pd.read_parquet("table_1/")
            df_2 = pd.read_parquet("table_2/")
            linker = Linker(
                [df_1, df_2],
                settings_dict,
                input_table_aliases=["customers", "contact_center_callers"]
                )
            ```
            Dedupe with a pre-trained model read from a json file
            ```py
            df = pd.read_csv("data_to_dedupe.csv")
            linker = Linker(df, "model.json")
            ```

        Args:
            input_table_or_tables (Union[str, list]): Input data into the linkage model.
                Either a single string (the name of a table in a database) for
                deduplication jobs, or a list of strings  (the name of tables in a
                database) for link_only or link_and_dedupe.  For some linkers, such as
                the DuckDBLinker and the SparkLinker, it's also possible to pass in
                dataframes (Pandas and Spark respectively) rather than strings.
            settings_dict (dict | Path | str): A Splink settings dictionary,
                or a path (either as a pathlib.Path object, or a string) to a json file
                defining a settings dictionary or pre-trained model.
            db_api (DatabaseAPI): A `DatabaseAPI` object, which manages interactions
                with the database. You can import these for use from
                `splink.backends.{your_backend}`
            set_up_basic_logging (bool, optional): If true, sets ups up basic logging
                so that Splink sends messages at INFO level to stdout. Defaults to True.
            input_table_aliases (Union[str, list], optional): Labels assigned to
                input tables in Splink outputs.  If the names of the tables in the
                input database are long or unspecific, this argument can be used
                to attach more easily readable/interpretable names. Defaults to None.
            validate_settings (bool, optional): When True, check your settings
                dictionary for any potential errors that may cause splink to fail.
        """
        ...
    
    def __deepcopy__(self, memo): # -> Self:
        """When we do EM training, we need a copy of the linker which is independent
        of the main linker e.g. setting parameters on the copy will not affect the
        main linker.  This method implements ensures linker can be deepcopied.
        """
        ...
    


