"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING
from splink.internals.graph_metrics import GraphMetricsResults
from splink.internals.splink_dataframe import SplinkDataFrame
from splink.internals.linker import Linker

if TYPE_CHECKING:
    ...
class LinkerClustering:
    """Cluster the results of the linkage model and analyse clusters, accessed via
    `linker.clustering`.
    """
    def __init__(self, linker: Linker) -> None:
        ...
    
    def cluster_pairwise_predictions_at_threshold(self, df_predict: SplinkDataFrame, threshold_match_probability: Optional[float] = ..., threshold_match_weight: Optional[float] = ...) -> SplinkDataFrame:
        """Clusters the pairwise match predictions that result from
        `linker.inference.predict()` into groups of connected record using the connected
        components graph clustering algorithm

        Records with an estimated `match_probability` at or above
        `threshold_match_probability` (or records with a `match_weight` at or above
        `threshold_match_weight`) are considered to be a match (i.e. they represent
        the same entity).

        Args:
            df_predict (SplinkDataFrame): The results of `linker.predict()`
            threshold_match_probability (float, optional): Pairwise comparisons with a
                `match_probability` at or above this threshold are matched
            threshold_match_weight (float, optional): Pairwise comparisons with a
                `match_weight` at or above this threshold are matched. Only one of
                threshold_match_probability or threshold_match_weight should be provided

        Returns:
            SplinkDataFrame: A SplinkDataFrame containing a list of all IDs, clustered
                into groups based on the desired match threshold.

        Examples:
            ```python
            df_predict = linker.inference.predict(threshold_match_probability=0.5)
            df_clustered = linker.clustering.cluster_pairwise_predictions_at_threshold(
                df_predict, threshold_match_probability=0.95
            )
            ```
        """
        ...
    
    def compute_graph_metrics(self, df_predict: SplinkDataFrame, df_clustered: SplinkDataFrame, *, threshold_match_probability: float = ...) -> GraphMetricsResults:
        """
        Generates tables containing graph metrics (for nodes, edges and clusters),
        and returns a data class of Splink dataframes

        Args:
            df_predict (SplinkDataFrame): The results of `linker.inference.predict()`
            df_clustered (SplinkDataFrame): The outputs of
                `linker.clustering.cluster_pairwise_predictions_at_threshold()`
            threshold_match_probability (float, optional): Filter the pairwise match
                predictions to include only pairwise comparisons with a
                match_probability at or above this threshold. If not provided, the value
                will be taken from metadata on `df_clustered`. If no such metadata is
                available, this value _must_ be provided.

        Returns:
            GraphMetricsResult: A data class containing SplinkDataFrames
            of cluster IDs and selected node, edge or cluster metrics.
                attribute "nodes" for nodes metrics table
                attribute "edges" for edge metrics table
                attribute "clusters" for cluster metrics table

        Examples:
            ```python
            df_predict = linker.inference.predict(threshold_match_probability=0.5)
            df_clustered = linker.clustering.cluster_pairwise_predictions_at_threshold(
                df_predict, threshold_match_probability=0.95
            )
            graph_metrics = linker.clustering.compute_graph_metrics(
                df_predict, df_clustered, threshold_match_probability=0.95
            )

            node_metrics = graph_metrics.nodes.as_pandas_dataframe()
            edge_metrics = graph_metrics.edges.as_pandas_dataframe()
            cluster_metrics = graph_metrics.clusters.as_pandas_dataframe()
            ```
        """
        ...
    


