"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from splink.internals.linker import Linker

if TYPE_CHECKING:
    ...
class LinkerMisc:
    """Miscellaneous methods on the linker that don't fit into other categories.
    Accessed via `linker.misc`.
    """
    def __init__(self, linker: Linker) -> None:
        ...
    
    def save_model_to_json(self, out_path: str | None = ..., overwrite: bool = ...) -> dict[str, Any]:
        """Save the configuration and parameters of the linkage model to a `.json` file.

        The model can later be loaded into a new linker using
        `Linker(df, settings="path/to/model.json", db_api=db_api).

        The settings dict is also returned in case you want to save it a different way.

        Examples:
            ```py
            linker.misc.save_model_to_json("my_settings.json", overwrite=True)
            ```
        Args:
            out_path (str, optional): File path for json file. If None, don't save to
                file. Defaults to None.
            overwrite (bool, optional): Overwrite if already exists? Defaults to False.

        Returns:
            dict: The settings as a dictionary.
        """
        ...
    
    def query_sql(self, sql, output_type=...): # -> SplinkDataFrame | DataFrame:
        """
        Run a SQL query against your backend database and return
        the resulting output.

        Examples:
            ```py
            linker = Linker(df, settings, db_api)
            df_predict = linker.inference.predict()
            linker.misc.query_sql(f"select * from {df_predict.physical_name} limit 10")
            ```

        Args:
            sql (str): The SQL to be queried.
            output_type (str): One of splink_df/splinkdf or pandas.
                This determines the type of table that your results are output in.
        """
        ...
    


