"""
This type stub file was generated by pyright.
"""

from typing import Any, TYPE_CHECKING
from splink.internals.charts import ChartReturnType
from splink.internals.cluster_studio import SamplingMethods
from splink.internals.splink_dataframe import SplinkDataFrame
from splink.internals.linker import Linker

if TYPE_CHECKING:
    ...
class LinkerVisualisations:
    """Visualisations to help you understand and diagnose your linkage model.
    Accessed via `linker.visualisations`.

    Most of the visualisations return an [altair.Chart](https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html)
    object, meaning it can be saved an manipulated using Altair.

    For example:

    ```py

    altair_chart = linker.visualisations.match_weights_chart()

    # Save to various formats
    altair_chart.save("mychart.png")
    altair_chart.save("mychart.html")
    altair_chart.save("mychart.svg")
    altair_chart.save("mychart.json")

    # Get chart spec as dict
    altair_chart.to_dict()
    ```


    To save the chart as a self-contained html file with all scripts
    inlined so it can be viewed offline:

    ```py
    from splink.internals.charts import save_offline_chart
    c = linker.visualisations.match_weights_chart()
    save_offline_chart(c.to_dict(), "test_chart.html")
    ```

    View resultant html file in Jupyter (or just load it in your browser)

    ```py
    from IPython.display import IFrame
    IFrame(src="./test_chart.html", width=1000, height=500)
    ```
    """
    def __init__(self, linker: Linker) -> None:
        ...
    
    def match_weights_chart(self, as_dict: bool = ...) -> ChartReturnType:
        """Display a chart of the (partial) match weights of the linkage model

        Args:
            as_dict (bool, optional): If True, return the chart as a dictionary.

        Examples:
            ```py
            altair_chart = linker.visualisations.match_weights_chart()
            altair_chart.save("mychart.png")
            ```
        Returns:
            altair_chart: An Altair chart
        """
        ...
    
    def m_u_parameters_chart(self, as_dict: bool = ...) -> ChartReturnType:
        """Display a chart of the m and u parameters of the linkage model

        Args:
            as_dict (bool, optional): If True, return the chart as a dictionary.

        Examples:
            ```py
            altair_chart = linker.visualisations.m_u_parameters_chart()
            altair_chart.save("mychart.png")
            ```

        Returns:
            altair_chart: An altair chart
        """
        ...
    
    def match_weights_histogram(self, df_predict: SplinkDataFrame, target_bins: int = ..., width: int = ..., height: int = ..., as_dict: bool = ...) -> ChartReturnType:
        """Generate a histogram that shows the distribution of match weights in
        `df_predict`

        Args:
            df_predict (SplinkDataFrame): Output of `linker.inference.predict()`
            target_bins (int, optional): Target number of bins in histogram. Defaults to
                30.
            width (int, optional): Width of output. Defaults to 600.
            height (int, optional): Height of output chart. Defaults to 250.
            as_dict (bool, optional): If True, return the chart as a dictionary.

        Examples:
            ```py
            df_predict = linker.inference.predict(threshold_match_weight=-2)
            linker.visualisations.match_weights_histogram(df_predict)
            ```
        Returns:
            altair_chart: An Altair chart

        """
        ...
    
    def parameter_estimate_comparisons_chart(self, include_m: bool = ..., include_u: bool = ..., as_dict: bool = ...) -> ChartReturnType:
        """Show a chart that shows how parameter estimates have differed across
        the different estimation methods you have used.

        For example, if you have run two EM estimation sessions, blocking on
        different variables, and both result in parameter estimates for
        first_name, this chart will enable easy comparison of the different
        estimates

        Args:
            include_m (bool, optional): Show different estimates of m values. Defaults
                to True.
            include_u (bool, optional): Show different estimates of u values. Defaults
                to False.
            as_dict (bool, optional): If True, return the chart as a dictionary.

        Examples:
            ```py
            linker.training.estimate_parameters_using_expectation_maximisation(
                blocking_rule=block_on("first_name"),
            )

            linker.training.estimate_parameters_using_expectation_maximisation(
                blocking_rule=block_on("surname"),
            )

            linker.visualisations.parameter_estimate_comparisons_chart()
            ```

        Returns:
            altair_chart: An Altair chart

        """
        ...
    
    def tf_adjustment_chart(self, output_column_name: str, n_most_freq: int = ..., n_least_freq: int = ..., vals_to_include: str | list[str] | None = ..., as_dict: bool = ...) -> ChartReturnType:
        """Display a chart showing the impact of term frequency adjustments on a
        specific comparison level.
        Each value

        Args:
            output_column_name (str): Name of an output column for which term frequency
                 adjustment has been applied.
            n_most_freq (int, optional): Number of most frequent values to show. If this
                 or `n_least_freq` set to None, all values will be shown.
                Default to 10.
            n_least_freq (int, optional): Number of least frequent values to show. If
                this or `n_most_freq` set to None, all values will be shown.
                Default to 10.
            vals_to_include (list, optional): Specific values for which to show term
                frequency adjustments.
                Defaults to None.
            as_dict (bool, optional): If True, return the chart as a dictionary.

        Examples:
            ```py
            linker.visualisations.tf_adjustment_chart("first_name")
            ```

        Returns:
            altair_chart: An Altair chart
        """
        ...
    
    def waterfall_chart(self, records: list[dict[str, Any]], filter_nulls: bool = ..., remove_sensitive_data: bool = ..., as_dict: bool = ...) -> ChartReturnType:
        """Visualise how the final match weight is computed for the provided pairwise
        record comparisons.

        Records must be provided as a list of dictionaries. This would usually be
        obtained from `df.as_record_dict(limit=n)` where `df` is a SplinkDataFrame.

        Examples:
            ```py
            df = linker.inference.predict(threshold_match_weight=2)
            records = df.as_record_dict(limit=10)
            linker.visualisations.waterfall_chart(records)
            ```

        Args:
            records (List[dict]): Usually be obtained from `df.as_record_dict(limit=n)`
                where `df` is a SplinkDataFrame.
            filter_nulls (bool, optional): Whether the visualisation shows null
                comparisons, which have no effect on final match weight. Defaults to
                True.
            remove_sensitive_data (bool, optional): When True, The waterfall chart will
                contain match weights only, and all of the (potentially sensitive) data
                from the input tables will be removed prior to the chart being created.
            as_dict (bool, optional): If True, return the chart as a dictionary.


        Returns:
            altair_chart: An Altair chart

        """
        ...
    
    def comparison_viewer_dashboard(self, df_predict: SplinkDataFrame, out_path: str, overwrite: bool = ..., num_example_rows: int = ..., return_html_as_string: bool = ...) -> str | None:
        """Generate an interactive html visualization of the linker's predictions and
        save to `out_path`.  For more information see
        [this video](https://www.youtube.com/watch?v=DNvCMqjipis)


        Args:
            df_predict (SplinkDataFrame): The outputs of `linker.predict()`
            out_path (str): The path (including filename) to save the html file to.
            overwrite (bool, optional): Overwrite the html file if it already exists?
                Defaults to False.
            num_example_rows (int, optional): Number of example rows per comparison
                vector. Defaults to 2.
            return_html_as_string: If True, return the html as a string

        Examples:
            ```py
            df_predictions = linker.predict()
            linker.visualisations.comparison_viewer_dashboard(
                df_predictions, "scv.html", True, 2
            )
            ```

            Optionally, in Jupyter, you can display the results inline
            Otherwise you can just load the html file in your browser

            ```py
            from IPython.display import IFrame
            IFrame(src="./scv.html", width="100%", height=1200)
            ```

        """
        ...
    
    def cluster_studio_dashboard(self, df_predict: SplinkDataFrame, df_clustered: SplinkDataFrame, out_path: str, sampling_method: SamplingMethods = ..., sample_size: int = ..., cluster_ids: list[str] = ..., cluster_names: list[str] = ..., overwrite: bool = ..., return_html_as_string: bool = ..., _df_cluster_metrics: SplinkDataFrame = ...) -> str | None:
        """Generate an interactive html visualization of the predicted cluster and
        save to `out_path`.

        Args:
            df_predict (SplinkDataFrame): The outputs of `linker.predict()`
            df_clustered (SplinkDataFrame): The outputs of
                `linker.cluster_pairwise_predictions_at_threshold()`
            out_path (str): The path (including filename) to save the html file to.
            sampling_method (str, optional): `random`, `by_cluster_size` or
                `lowest_density_clusters_by_size`. Defaults to `random`.
            sample_size (int, optional): Number of clusters to show in the dahboard.
                Defaults to 10.
            cluster_ids (list): The IDs of the clusters that will be displayed in the
                dashboard.  If provided, ignore the `sampling_method` and `sample_size`
                arguments. Defaults to None.
            overwrite (bool, optional): Overwrite the html file if it already exists?
                Defaults to False.
            cluster_names (list, optional): If provided, the dashboard will display
                these names in the selection box. Ony works in conjunction with
                `cluster_ids`.  Defaults to None.
            return_html_as_string: If True, return the html as a string

        Examples:
            ```py
            df_p = linker.inference.predict()
            df_c = linker.visualisations.cluster_pairwise_predictions_at_threshold(
                df_p, 0.5
            )

            linker.cluster_studio_dashboard(
                df_p, df_c, [0, 4, 7], "cluster_studio.html"
            )
            ```

            Optionally, in Jupyter, you can display the results inline
            Otherwise you can just load the html file in your browser

            ```py
            from IPython.display import IFrame
            IFrame(src="./cluster_studio.html", width="100%", height=1200)
            ```
        """
        ...
    


