"""Compatibility facade for Splink runtime exports."""

from .splink_runtime import (
    comparison_level_key,
    comparison_level_keys,
    splink_dedupe_job,
    splink_visualize_job,
    run_splink,
    BlockingRuleLike,
    TrainingBlockToComparisonLevelMap,
    SplinkChartType,
    PredictionInputTableName,
    PredictionInputTableNames,
    PairsTableName,
    ClustersTableName,
    UniquePairsTableName,
    BlockedPairsTableName,
    DoNotLinkTableName,
    ComparisonLevelKey,
    PostTrainRatioCopyComparisons,
)

__all__ = [
    "comparison_level_key",
    "comparison_level_keys",
    "splink_dedupe_job",
    "splink_visualize_job",
    "run_splink",
    "BlockingRuleLike",
    "TrainingBlockToComparisonLevelMap",
    "SplinkChartType",
    "PredictionInputTableName",
    "PredictionInputTableNames",
    "PairsTableName",
    "ClustersTableName",
    "UniquePairsTableName",
    "BlockedPairsTableName",
    "DoNotLinkTableName",
    "ComparisonLevelKey",
    "PostTrainRatioCopyComparisons",
]
