"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
#from splink.internals.blocking_rule_library import block_on
#from splink.internals.column_expression import ColumnExpression
from splink.internals.database_api import DatabaseAPI
# from splink.internals.datasets import splink_datasets
from splink.internals.linker import Linker
#from splink.internals.settings_creator import SettingsCreator
from splink.internals.splink_dataframe import SplinkDataFrame
#from splink.internals.duckdb.database_api import DuckDBAPI
#from splink.internals.spark.database_api import SparkAPI

class DuckDBAPI(DatabaseAPI):
    """
    stub
    """
    def __init__(self, connection): ...
    def table_exists_in_database(self, table_name: str) -> bool: ...
    def table_to_splink_dataframe(self, templated_name: str, physical_name: str) -> SplinkDataFrame: ...

class SparkAPI:
    """
    stub
    """

if TYPE_CHECKING:
    ...
def __getattr__(name): # -> type[SparkAPI] | type[DuckDBAPI]:
    ...

__version__ = ...
__all__ = ["DuckDBAPI", "Linker", "SparkAPI"]
