"""
This type stub file was generated by pyright.
"""

#__all__ = ["NullLevel", "ElseLevel", "CustomLevel", "ExactMatchLevel", "LiteralMatchLevel", "ColumnsReversedLevel", "LevenshteinLevel", "DamerauLevenshteinLevel", "JaroWinklerLevel", "JaroLevel", "JaccardLevel", "DistanceFunctionLevel", "PairwiseStringDistanceFunctionLevel", "AbsoluteTimeDifferenceLevel", "AbsoluteDateDifferenceLevel", "DistanceInKMLevel", "ArrayIntersectLevel", "ArraySubsetLevel", "PercentageDifferenceLevel", "AbsoluteDifferenceLevel", "And", "Not", "Or", "CosineSimilarityLevel"]
