"""
This type stub file was generated by pyright.
"""



def apply(loop=...): # -> None:
    """Patch asyncio to make its event loop reentrant."""
    ...

def replace_refs(
    obj,
    base_uri="",
    loader=None,
    jsonschema=False,
    load_on_repr=True,
    merge_props=False,
    proxies=True,
    lazy_load=True
):
    """
    stub
    """
    ...