"""
This type stub file was generated by pyright.
"""

import asyncio
import asyncio.events as events
import os
import sys
import threading
from contextlib import contextmanager, suppress
from heapq import heappop
from typing import Any

def apply(loop=...): # -> None:
    """Patch asyncio to make its event loop reentrant."""
    ...

def replace_refs(
    obj,
    base_uri="",
    loader=None,
    jsonschema=False,
    load_on_repr=True,
    merge_props=False,
    proxies=True,
    lazy_load=True
):
    """
    stub
    """
    ...